apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: seleniumhubs.selenium.hub.com
spec:
  group: selenium.hub.com
  names:
    kind: SeleniumHub
    listKind: SeleniumHubList
    plural: seleniumhubs
    singular: seleniumhub
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
